"""empty message

Revision ID: 6bf7c0ceb3ef
Revises: 818d6081f2d1
Create Date: 2025-01-24 19:56:26.633871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf7c0ceb3ef'
down_revision: Union[str, None] = '818d6081f2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelduled_workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('shelduled_date', sa.Date(), nullable=False),
    sa.Column('shelduled_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False, default='pending'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


    """    id = Column(Integer, primary_key=True, nullable=False)
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    workout_plan_id = Column(Integer, ForeignKey('workouts_plans.id'), nullable=False)
    shelduled_date = Column(Date, nullable=False, default=date)
    shelduled_time = Column(Time, nullable=False, default=time)
    status = Column(String, nullable=False, default='pending')"""
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
